spring.application.name=bus_ticket_pro

server.port=8080

spring.datasource.url = jdbc:mysql://localhost:3306/bus_ticket_pro?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username = root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache = false

# ============================================================
# PayOS Configuration — điền 3 giá trị bên dưới từ my.payos.vn
# ============================================================
payos.client-id=d4765a7f-5c1c-4e54-bb0e-57e8853f05f8
payos.api-key=b2eb418a-2313-43c0-94d8-7216a72e11e7
payos.checksum-key=91017166576ff933f6b4f9ac0dd6b6e4563a42325efe5055518fd2f451c3fff4
payos.return-url=https://relocate-tropical-skied.ngrok-free.dev/payment/success
payos.cancel-url=https://relocate-tropical-skied.ngrok-free.dev/payment/cancel

# ============================================================
# EmailJS Configuration
# ============================================================
emailjs.service-id=service_3yke50g
emailjs.template-id=template_mcutrc8
emailjs.public-key=mhVhUeI-C6HkEfVNy
emailjs.private-key=lhAfrXJWJpwyWGhFxSHnY